export const metadata = {
    title: 'Terms & Conditions — Brandverse',
    description: 'Terms and conditions for using Brandverse AI voice agent services.',
};

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-[#020617] text-slate-300 py-20 px-6">
            <div className="max-w-4xl mx-auto space-y-12">
                <div className="space-y-4">
                    <h1 className="text-5xl font-black text-white tracking-tighter uppercase">Terms & Conditions</h1>
                    <p className="text-blue-400 font-bold uppercase tracking-widest text-sm">Last updated: December 23, 2025</p>
                </div>

                <section className="space-y-6">
                    <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                        <span className="w-8 h-8 rounded-lg bg-blue-600/20 flex items-center justify-center text-blue-400 text-sm">01</span>
                        Agreement to Terms
                    </h2>
                    <div className="pl-11 text-slate-400">
                        <p>By accessing or using the Brandverse.tech AI automation platform, you agree to be bound by these Terms and Conditions and our Privacy Policy. These terms apply to all visitors, clients, and others who access the service.</p>
                    </div>
                </section>

                <section className="space-y-6">
                    <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                        <span className="w-8 h-8 rounded-lg bg-blue-600/20 flex items-center justify-center text-blue-400 text-sm">02</span>
                        AI Service Usage and Compliance
                    </h2>
                    <div className="pl-11 space-y-4">
                        <p>Our AI voice agents are designed for business automation and lead generation. You agree to:</p>
                        <ul className="list-disc space-y-2 text-slate-400">
                            <li>Comply with all local telecommunications laws (including TCPA and GDPR).</li>
                            <li>Ensure all scripts and AI behaviors used are truthful and not misleading.</li>
                            <li>Use the service only for lawful business purposes.</li>
                            <li>Take full responsibility for the outcomes of AI-driven client interactions.</li>
                        </ul>
                    </div>
                </section>

                <section className="space-y-6">
                    <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                        <span className="w-8 h-8 rounded-lg bg-blue-600/20 flex items-center justify-center text-blue-400 text-sm">03</span>
                        Intellectual Property
                    </h2>
                    <div className="pl-11 text-slate-400 space-y-4">
                        <p>The Brandverse platform, including but not limited to AI algorithms, proprietary code, design assets, and software, is the exclusive property of Brandverse.</p>
                        <p>Clients are granted a limited license to use the output generated by our AI agents specifically for their business operations as defined in their service agreement.</p>
                    </div>
                </section>

                <section className="space-y-6">
                    <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                        <span className="w-8 h-8 rounded-lg bg-blue-600/20 flex items-center justify-center text-blue-400 text-sm">04</span>
                        Limitation of Liability
                    </h2>
                    <div className="pl-11 text-slate-400">
                        <p>Brandverse shall not be liable for any indirect, incidental, special, or consequential damages resulting from the use of our AI services, including any actions taken by AI agents during client calls or processing errors.</p>
                    </div>
                </section>

                <section className="space-y-4 text-slate-500 text-sm italic border-t border-white/5 pt-12">
                    <p>These terms are governed by the laws of the jurisdiction in which Brandverse operates. We reserve the right to modify these terms at any time.</p>
                </section>
            </div>
        </div>
    );
}
