'use client';

import { Shield, Lock, Eye } from 'lucide-react';

declare global {
    interface Window {
        Cookiebot?: any;
    }
}

export default function CookiesPage() {
    return (
        <div className="min-h-screen bg-[#020617] text-slate-300 py-32 px-6">
            <div className="max-w-4xl mx-auto space-y-16">
                {/* Header */}
                <section className="space-y-6 text-center">
                    <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-[10px] font-black uppercase tracking-[0.2em]">
                        Data Architecture
                    </div>
                    <h1 className="text-5xl md:text-7xl font-black text-white tracking-tighter uppercase italic">Cookie <span className="text-blue-500">Declaration.</span></h1>
                    <p className="text-xl text-slate-400 font-bold max-w-2xl mx-auto leading-relaxed">
                        Transparent data protocols for a <span className="text-blue-400">Next-Gen</span> browsing experience. We don't hide our tech.
                    </p>
                </section>

                {/* Main Content */}
                <div className="grid gap-12">
                    <section className="p-10 rounded-[3rem] bg-[#020617] border border-white/5 space-y-8 relative overflow-hidden group">
                        <div className="absolute top-0 right-0 p-12 opacity-5 translate-x-10 -translate-y-10 group-hover:translate-x-0 group-hover:translate-y-0 transition-transform">
                            <Shield className="w-48 h-48 text-blue-500" />
                        </div>
                        <h2 className="text-3xl font-black text-white uppercase italic tracking-tighter flex items-center gap-4">
                            <div className="w-10 h-10 rounded-xl bg-blue-600/20 flex items-center justify-center text-blue-400 text-sm">01</div>
                            Operational Protocol
                        </h2>
                        <p className="text-slate-400 text-lg font-bold leading-relaxed relative z-10">
                            Cookies are small data fragments stored on your device to enhance system performance. At Brandverse, we categorize these into <span className="text-blue-400">Necessary</span>, <span className="text-blue-400">Statistics</span>, and <span className="text-blue-400">Marketing</span> layers.
                        </p>
                    </section>

                    {/* LIVE AUDIT INJECTION POINT */}
                    <section className="p-10 rounded-[3rem] bg-[#020617] border border-white/5 space-y-8 relative overflow-hidden group">
                        <div className="absolute top-0 right-0 p-12 opacity-5 translate-x-10 -translate-y-10 group-hover:translate-x-0 group-hover:translate-y-0 transition-transform">
                            <Eye className="w-48 h-48 text-indigo-500" />
                        </div>
                        <h2 className="text-3xl font-black text-white uppercase italic tracking-tighter flex items-center gap-4">
                            <div className="w-10 h-10 rounded-xl bg-indigo-600/20 flex items-center justify-center text-indigo-400 text-sm">02</div>
                            System Audit
                        </h2>
                        <div className="relative z-10 bg-black/40 rounded-2xl p-6 border border-white/5">
                            <p className="text-slate-500 text-sm font-bold italic mb-6">
                                The following table is dynamically generated by our Consent Management Architect (Cookiebot).
                            </p>
                            {/* Injects the Cookiebot declaration script */}
                            <div id="CookieDeclaration" className="text-slate-400 text-sm font-medium">
                                <script id="CookieDeclaration" src={`https://consent.cookiebot.com/${process.env.NEXT_PUBLIC_COOKIEBOT_ID}/cd.js`} type="text/javascript" async></script>
                            </div>
                        </div>
                    </section>

                    <section className="p-10 rounded-[3rem] bg-[#020617] border border-white/5 space-y-8 relative overflow-hidden group">
                        <div className="absolute top-0 right-0 p-12 opacity-5 translate-x-10 -translate-y-10 group-hover:translate-x-0 group-hover:translate-y-0 transition-transform">
                            <Lock className="w-48 h-48 text-purple-500" />
                        </div>
                        <h2 className="text-3xl font-black text-white uppercase italic tracking-tighter flex items-center gap-4">
                            <div className="w-10 h-10 rounded-xl bg-purple-600/20 flex items-center justify-center text-purple-400 text-sm">03</div>
                            Your Controls
                        </h2>
                        <p className="text-slate-400 text-lg font-bold leading-relaxed relative z-10">
                            You have absolute sovereignty over your data. You can adjust your preferences at any time by clearing your browser cache or interacting with our dynamic consent module.
                        </p>
                        <div className="pt-6">
                            <button
                                onClick={() => {
                                    if (window.Cookiebot) window.Cookiebot.renew();
                                }}
                                className="px-8 py-4 bg-white/5 border border-white/10 rounded-2xl text-white font-black uppercase tracking-widest text-[10px] hover:bg-white/10 transition-all"
                            >
                                Reconfigure Consent Module
                            </button>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
}
